# Generated by Django 5.2.7 on 2025-10-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='selected_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('N', 'Not Marked')], default='N', max_length=1, null=True),
        ),
    ]
