# Generated by Django 5.2.7 on 2025-10-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userresponse_selected_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('outstanding', 'Outstanding'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], max_length=20)),
                ('feedback_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
