# Generated by Django 5.2.7 on 2025-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
