# Generated by Django 5.2.7 on 2025-10-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='image_url',
        ),
    ]
