# Generated by Django 5.2.7 on 2025-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_image_question_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Exam', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('submission_start', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
