# Generated by Django 5.2.7 on 2025-10-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_examconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examconfig',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examconfig',
            name='start_time',
        ),
        migrations.AddField(
            model_name='examconfig',
            name='exam_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examconfig',
            name='exam_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examconfig',
            name='name',
            field=models.CharField(default='Default Exam', max_length=100),
        ),
    ]
