# Generated by Django 5.2.7 on 2025-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_examconfig_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('marks', models.IntegerField(choices=[(1, '1 Mark'), (2, '2 Marks')])),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
