# Generated by Django 5.2.7 on 2025-10-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_iotquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='questions',
            field=models.ManyToManyField(to='core.iotquestion'),
        ),
    ]
