# Generated by Django 5.2.7 on 2025-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_examsession_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='questions',
            field=models.ManyToManyField(to='core.question'),
        ),
    ]
